// The learning path, in order. The viewer reads this list to build the sidebar,
// track progress, and remind you not to skip ahead.
//
// `js` lists the JavaScript concepts each lesson teaches before its React part.

export const steps = [
  {
    id: '01',
    level: 'Basics',
    file: 'lessons/01-jsx.jsx',
    title: 'JSX & rendering',
    goal: 'Describe UI with JSX and drop JavaScript into it with { }.',
    js: ['const & let', 'arrow functions', 'template literals', 'expressions & the ternary'],
  },
  {
    id: '02',
    level: 'Basics',
    file: 'lessons/02-components.jsx',
    title: 'Components',
    goal: 'Build a UI out of small, named, reusable functions.',
    js: ['modules: import & export'],
  },
  {
    id: '03',
    level: 'Basics',
    file: 'lessons/03-props.jsx',
    title: 'Props',
    goal: 'Pass data from a parent component to its children.',
    js: ['objects', 'object destructuring', 'shorthand properties', 'object spread & rest'],
  },
  {
    id: '04',
    level: 'Basics',
    file: 'lessons/04-events.jsx',
    title: 'Event handling',
    goal: 'Respond to clicks, typing and form submits.',
    js: ['functions as values', 'callbacks', 'passing vs. calling', 'closures'],
  },
  {
    id: '05',
    level: 'Basics',
    file: 'lessons/05-state.jsx',
    title: 'State (useState)',
    goal: 'Make components remember values and update the screen.',
    js: ['array destructuring', 'references & ===', 'immutable updates with spread', 'snapshots'],
  },
  {
    id: '06',
    level: 'Intermediate',
    file: 'lessons/06-conditional-rendering.jsx',
    title: 'Conditional rendering',
    goal: 'Show different UI depending on state and props.',
    js: ['truthy & falsy', '&& and ||', '?? (nullish)', '?. (optional chaining)'],
  },
  {
    id: '07',
    level: 'Intermediate',
    file: 'lessons/07-lists-and-keys.jsx',
    title: 'Lists & keys',
    goal: 'Render arrays of data and update them without mutating.',
    js: ['map', 'filter', 'find', 'some', 'reduce', 'toSorted'],
  },
  {
    id: '08',
    level: 'Intermediate',
    file: 'lessons/08-forms.jsx',
    title: 'Forms',
    goal: 'Build controlled inputs, validate, and submit.',
    js: ['computed property names', 'string methods', 'Number()', 'Object.keys'],
  },
  {
    id: '09',
    level: 'Intermediate',
    file: 'lessons/09-useEffect.jsx',
    title: 'Side effects (useEffect)',
    goal: 'Sync with the outside world: fetching, timers, the page title.',
    js: ['timers', 'promises', 'async / await', 'try / catch', 'fetch'],
  },
  {
    id: '10',
    level: 'Intermediate',
    file: 'lessons/10-hooks-and-refs.jsx',
    title: 'Hooks: rules & useRef',
    goal: 'Know why hook order matters; use refs for DOM access and silent values.',
    js: ['how hooks work in plain JS (closures + arrays)'],
  },
  {
    id: '11',
    level: 'Advanced',
    file: 'lessons/11-context.jsx',
    title: 'Context API',
    goal: 'Share data with deeply nested components without prop drilling.',
    js: ['objects that bundle data and functions'],
  },
  {
    id: '12',
    level: 'Advanced',
    file: 'lessons/12-custom-hooks.jsx',
    title: 'Custom hooks',
    goal: 'Package reusable stateful logic into your own use… functions.',
    js: ['JSON.stringify & JSON.parse', 'localStorage', 'lazy initial values'],
  },
  {
    id: '13',
    level: 'Advanced',
    file: 'lessons/13-performance.jsx',
    title: 'Performance',
    goal: 'Find and fix unnecessary re-renders with memo, useMemo and useCallback.',
    js: ['=== on objects & functions', 'shallow comparison', 'measuring time'],
  },
];
